# Filename: Dockerfile.ui

# 1. Build Stage
FROM node:20-alpine AS build
WORKDIR /app

# Copy package.json and package-lock.json first to leverage Docker cache
COPY sk-fabricator-ui/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the UI app source code
COPY sk-fabricator-ui/ .

# Build the app (this runs 'ng build')
RUN npm run build

# 2. Production Stage
FROM node:20-alpine AS final
WORKDIR /app

# Copy package.json and package-lock.json for production dependencies
COPY sk-fabricator-ui/package*.json ./

# Install *only* production dependencies
RUN npm install --omit=dev

# Copy build artifacts from the build stage
COPY --from=build /app/dist/ ./dist/

# Command to run the SSR server
CMD [ "npm", "run", "serve:ssr:sk-fabricator-ui" ]