FROM node:20-alpine AS build
WORKDIR /app

COPY sk-fabricator-ui/package*.json ./
RUN npm install
COPY sk-fabricator-ui/ ./
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist/sk-fabricator-ui/browser /usr/share/nginx/html
COPY sk-fabricator-ui/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]