# Filename: Dockerfile.ui

# 1. Build Stage
FROM node:lts-alpine AS build
WORKDIR /app

# Copy package files from the sub-directory
COPY sk-fabricator-ui/package.json sk-fabricator-ui/package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the UI app source code
COPY sk-fabricator-ui/ .

# Build the app (this runs 'ng build')
RUN npm run build

# 2. Production Stage
FROM node:lts-alpine AS final
WORKDIR /app

# Install *only* production dependencies
COPY sk-fabricator-ui/package.json sk-fabricator-ui/package-lock.json ./
RUN npm install --omit=dev

# Copy build artifacts from the build stage
COPY --from=build /app/dist/ ./dist/

# Command to run the SSR server
CMD [ "npm", "run", "serve:ssr:sk-fabricator-ui" ]