services:
  - type: web
    name: skfabricatorapi
    env: docker
    dockerfilePath: Dockerfile.api
    healthCheckPath: /health
    ports:
      - 10000
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Host=dpg-d45iievdiees7389up0g-a.singapore-postgres.render.com;Port=5432;Database=skfabricatordb;Username=skfabricatordb_user;Password=iWQWI4mq2VqeXEsu2kLz4RG6PHEzjjpL
      - key: Jwt__Issuer
        value: https://skfabricatorapi.onrender.com # Will be updated by Render after deployment
      - key: Jwt__Audience
        value: https://skfabricatorui.onrender.com # Will be updated by Render after deployment
      - key: Jwt__Key
        generateValue: true
      - key: CloudinarySettings__CloudName
      - key: CloudinarySettings__ApiKey
      - key: CloudinarySettings__ApiSecret
      - key: Email__From
      - key: Email__To
      - key: Email__SmtpServer
      - key: Email__SmtpPort
      - key: Email__Username
      - key: Email__Password
  - type: static_site
    name: skfabricatorui
    env: static
    buildCommand: npm install && npm run build
    publishPath: dist/sk-fabricator-ui/browser
    routes:
      - type: rewrite
        source: /api/*
        destination: https://skfabricatorapi.onrender.com/api/* # This will be updated by Render after deployment
    envVars:
      - key: API_URL
        value: https://skfabricatorapi.onrender.com # This will be updated by Render after deployment
