services:
  - type: web
    name: skfabricatorapi
    env: docker
    dockerfilePath: SkFabricatorApi/Dockerfile
    healthCheckPath: /health
    ports: 10000
    envVars:
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/data/SkFabricator.db
      - key: Jwt__Issuer
        value: http://skfabricatorapi:10000
      - key: Jwt__Audience
        value: http://skfabricatorui:80
      - key: Jwt__Key
        generateValue: true
      - key: CloudinarySettings__CloudName
        sync: false
      - key: CloudinarySettings__ApiKey
        sync: false
      - key: CloudinarySettings__ApiSecret
        sync: false
      - key: Email__From
        sync: false
      - key: Email__To
        sync: false
      - key: Email__SmtpServer
        sync: false
      - key: Email__SmtpPort
        sync: false
      - key: Email__Username
        sync: false
      - key: Email__Password
        sync: false
    disks:
      - name: skfabricator-data
        path: /data

  - type: web
    name: skfabricatorui
    env: docker
    dockerfilePath: sk-fabricator-ui/Dockerfile
    healthCheckPath: /
    ports: 80
    envVars:
      - key: API_URL
        value: http://skfabricatorapi:10000
