name: Build and Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: ghcr.io/${{ github.repository }}/skfabricatorapi:latest

      - name: Deploy to Render
        uses: render-actions/deploy@v1.4.0
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID_API }}
          api-key: ${{ secrets.RENDER_API_KEY }}